spring.datasource.url=${DATABASE_URL}
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.ssl.enabled=true

# Production Frontend & CORS
app.frontend-url=${FRONTEND_URL}
app.frontend-redirect-url=${FRONTEND_URL}/oauth2/redirect
jobrunr.dashboard.enabled=false
