spring.datasource.url=jdbc:sqlite:berry.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.name= ${testname}
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# jobrunner
jobrunr.background-job-server.enabled=true
jobrunr.dashboard.enabled=true

jobrunr.database.type=mem

